### ISSUE TITLE
How to generate more captions

### ISSUE THREAD

**Issue by victorup** [davidnvq/grit#21]
Hello,

I would like to generate multiple candidate captions for one image when doing image captioning. How could I do this? Is there any parameter I can set?

Thanks!

**Comment by davidnvq** [comment]
I'm sorry for the late reply. Indeed, only one caption is generated by default. 
In order to generate multiple captions per image, you need to put some effort with Beamsearch.
Please help yourself first with your implementation. 

![image](https://user-images.githubusercontent.com/30741785/206851977-a2e34919-0185-44a5-bc24-0e25425ed845.png)

**Comment by taruntiwarihp** [comment]
Hi @davidnvq, I want to increase the length of the generated caption, do I need to train it again or do you have any idea, Please, thanks

**Comment by yan1617262965** [comment]
@victorup 
Hello, have you implemented generating multiple captions
